### ISSUE TITLE
Whitespace character hack

### ISSUE THREAD

**Issue by WangNianyi2001** [ljharb/is-arrow-function#12]
I noticed that you use `/^\([^)]*\) *=>/` to detect an arrow function header with parenthesis.
However, there are many other white space characters can be used as the separator between the close parenthesis and the equal sign, as long as it does not start a new line, e.g. `\t`.

`/^\([^)]*\)\s(?=(?<![\n\r]).)*=>/` is recommended.
In this case, the `\s(?=(?<![\n\r]).)` part represents a white space character which is neither `\n` or `\r`.

`[ \t\f\v]` would also do the work, but it just does not look flexible.

**Comment by ljharb** [comment]
Can you provide a failing test case?

**Comment by WangNianyi2001** [comment]
Function.prototype.toString.call(()	=>	1).search('\t')

**Comment by ljharb** [comment]
That currently passes my tests. Could you try making a PR with test cases that fails?

**Comment by WangNianyi2001** [comment]
Ooh, I've tested again, and found out that Js engine would actually convert any white space characters before `=>` into pure spaces. My bad. Sorry for the interruptions.
