### ISSUE TITLE
Unpublish in favor of is-arrowfunction

### ISSUE THREAD

**Issue by steelbrain** [ljharb/is-arrow-function#3]
It's a one liner and works in every spec compliant browser. https://github.com/steelbrain/is-arrowfunction

**Comment by ljharb** [comment]
If you have an improvement, the polite thing to do is PR it in, not to (rudely) suggest unpublishing in favor of your super-brand-new module that has zero tests.

There are more engines than "spec-compliant" ones considering no engine exists that is even compliant with ES5. If you sent a PR, which included detailed browser testing, including that `isArrowFunction(window.alert)` returns `false` (it doesn't, in your module), I'd definitely consider it.

**Comment by steelbrain** [comment]
Oh wow, I honestly didn't know that native functions too don't have a prototype. Thanks for pointing me in the right direction, unpublished my module in favor of yours.

**Comment by ljharb** [comment]
np, i'm always happy to consider improvements to any of my modules, so if you can find a way to maintain a module's semantics and robustness that makes it more lightweight, I'm happy for the contribution!
