### ISSUE TITLE
Fails for async arrow functions

### ISSUE THREAD

**Issue by damianobarbati** [ljharb/is-arrow-function#6]
Hey, the checker fails for async arrow functions which are arrow functions as well!

```async () => {}```

**Comment by ljharb** [comment]
In what engine is this the case? Are you using Babel?

My tests seem to pass locally.

**Comment by ljharb** [comment]
(Will reopen if you can provide more information)

**Comment by damianobarbati** [comment]
@ljharb correct: babel transpiling is killing it (y)

**Comment by ljharb** [comment]
@damianobarbati this package is for identifying native things at runtime; transpiled async functions end up as normal functions, so they can't be identified as async at runtime.

**Comment by damianobarbati** [comment]
Correct: sorry for bothering!
